name: Build Dylib

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build iOS Dylib
      run: |
        if [ ! -f "main.m" ]; then
          echo "main.m file not found!"
          exit 1
        fi

        echo "Compiling main.m for iOS arm64..."
        clang -dynamiclib \
          -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -arch arm64 \
          -miphoneos-version-min=14.0 \
          -Wno-error=implicit-function-declaration \
          -Wno-implicit-function-declaration \
          -Wno-int-to-pointer-cast \
          -framework Foundation \
          -framework UIKit \
          -o libhook.dylib main.m

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dylib-file
        path: libhook.dylib
