name: Build Dylib

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2

    - name: Compile iOS Dylib
      run: |
        clang -dynamiclib \
          -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -arch arm64 \
          -miphoneos-version-min=14.0 \
          -Wno-everything \
          -framework Foundation \
          -framework UIKit \
          -o libhook.dylib main.m

    - name: Upload Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: dylib-file
        path: libhook.dylib
